"""empty message

Revision ID: 0948c9a49f84
Revises: bf8db2f1856b
Create Date: 2020-06-11 23:11:51.755700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0948c9a49f84'
down_revision = 'bf8db2f1856b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
