"""empty message

Revision ID: 4fc2e0283e70
Revises: 0948c9a49f84
Create Date: 2020-07-03 21:57:49.106959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc2e0283e70'
down_revision = '0948c9a49f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('sections', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'sections')
    # ### end Alembic commands ###
