"""empty message

Revision ID: 8c767813f419
Revises: b8326fdb56b6
Create Date: 2020-05-16 00:19:29.924795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c767813f419'
down_revision = 'b8326fdb56b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'category')
    # ### end Alembic commands ###
