"""empty message

Revision ID: 8f9e9fc3d99b
Revises: d7f59e5e6fd0
Create Date: 2020-05-27 20:26:22.668496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9e9fc3d99b'
down_revision = 'd7f59e5e6fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    # ### end Alembic commands ###
