"""empty message

Revision ID: b8326fdb56b6
Revises: 6b4c2d1603a9
Create Date: 2020-05-16 00:14:45.856526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8326fdb56b6'
down_revision = '6b4c2d1603a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Recipe_category_id_fkey', 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Recipe_category_id_fkey', 'Recipe', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
