"""empty message

Revision ID: bf8db2f1856b
Revises: 8f9e9fc3d99b
Create Date: 2020-06-01 14:22:47.663908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8db2f1856b'
down_revision = '8f9e9fc3d99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'confirmation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirmation', type_='foreignkey')
    op.drop_column('confirmation', 'user_id')
    # ### end Alembic commands ###
