"""empty message

Revision ID: d7f59e5e6fd0
Revises: 50acef6ae4c5
Create Date: 2020-05-27 19:53:44.020368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f59e5e6fd0'
down_revision = '50acef6ae4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('validated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'validated')
    # ### end Alembic commands ###
