"""empty message

Revision ID: 2d54a1e8d7be
Revises: 21e3ff3cd08b
Create Date: 2020-05-14 21:39:09.849860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d54a1e8d7be'
down_revision = '21e3ff3cd08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
