"""empty message

Revision ID: 468cfe9e5bbd
Revises: 91d9aa7079ec
Create Date: 2020-05-01 19:53:12.462170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468cfe9e5bbd'
down_revision = '91d9aa7079ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recipe')
    # ### end Alembic commands ###
