"""empty message

Revision ID: 51b20a22189c
Revises: 2d54a1e8d7be
Create Date: 2020-05-15 22:09:04.708870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b20a22189c'
down_revision = '2d54a1e8d7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('ingredients', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'ingredients')
    # ### end Alembic commands ###
