"""empty message

Revision ID: 5781c28b2779
Revises: 6200cd4082bc
Create Date: 2020-05-02 20:34:29.320209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5781c28b2779'
down_revision = '6200cd4082bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recipe', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.drop_column('Recipe', 'category_id')
    # ### end Alembic commands ###
