"""empty message

Revision ID: 6200cd4082bc
Revises: 74edd62eb77a
Create Date: 2020-05-02 20:10:06.478227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6200cd4082bc'
down_revision = '74edd62eb77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Recipe', 'cook_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Recipe', 'cook_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
